name: BMO CI

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff==0.15.13 python-dotenv

      - name: Debug Ruff
        run: |
          which ruff
          ruff --version

      - name: Run Ruff
        run: |
          ruff check .
          ruff format . --check

      - name: Run tests
        run: |
          pytest tests/ -v
